### PR TITLE
Update jdk to upstream version 1.8.0-60

### PR DESCRIPTION
**Pull request by brevilo**

### CODE REVIEW

**Comment by brevilo** [comment]
I couldn't really test it locally but the URL and the sha256sum are correct...

**Comment by sjackman** [comment]
The git log message should be simply `jdk 1.8.0-60`

**Comment by sjackman** [comment]
Thanks for your contribution, Oliver.

**Comment by brevilo** [comment]
The git log message should be simply jdk 1.8.0-60

Next time :smile:

**Pull request closed without merging**
