### PR TITLE
install: list basic dependencies

### PR DESCRIPTION
**Pull request by dunn**
followup to #333

### CODE REVIEW

**Comment by sjackman** [comment]
Thanks for this, Alex. Please remove the style-only changes from the patch. If they're from the upstream `go` branch, I'll merge them in a separate commit.

**Comment by dunn** [comment]
Upstream is using a separate repository for the install script now, rather than the `go` branch, so I wasn't sure if it was still a priority to keep the branches in sync.

**Comment by sjackman** [comment]
I'd rather keep the patch small. It makes it easier to review.

**Comment by dunn** [comment]
Done.

**Comment by sjackman** [comment]
Thanks, Alex.

**Pull request merged**
