### PR TITLE
nethogs 0.8.1 (new formula)

### PR DESCRIPTION
**Pull request by Rudloff**

### CODE REVIEW

**Comment by sjackman** [comment]
Can this formula be built on Mac OS? If so this formula should be submitted to Homebrew/homebrew. Please read CONTRIBUTING.md

**Comment by Rudloff** [comment]
I am not sure nethogs works on OSX but I will try to build it.

**Comment by Rudloff** [comment]
Like I thought, the current nethogs does not work on OSX.
But I submitted a patch to add OSX compatibility: https://github.com/raboof/nethogs/pull/20

**Comment by sjackman** [comment]
Nicely done, and your patch was merged upstream. With the next stable release of nethogs including your patch, please submit to Homebrew.

**Pull request closed without merging**
