### PR TITLE
fontconfig: set POSIXLY_CORRECT when building

### PR DESCRIPTION
**Pull request by ntkme**

### CODE REVIEW

**Comment by sjackman** [comment]
Hi, @ntkme Does this patch work around some error message that you're seeing?

**Comment by ntkme** [comment]
@sjackman I just tested on another Linux distro, and it failed because of following:

```
grep: character class syntax is [[:space:]], not [:space:]
```

`ENV["POSIXLY_CORRECT"]` fixed it, so I updated the patch.

**Comment by sjackman** [comment]
On which Linux distribution did you see that error?

**Comment by ntkme** [comment]
CentOS 6 with brewed `grep`. System `grep` doesn't have this problem.

**Comment by sjackman** [comment]
Can you please report the output of `brew gist-logs fontconfig`?

**Comment by ntkme** [comment]
https://gist.github.com/anonymous/b1aa70bf6a0530737221

**Comment by sjackman** [comment]
https://gist.github.com/anonymous/b1aa70bf6a0530737221#file-02-make-L316-L326
```
docbook2man local-fontconfig-user.sgml && \
rm -f manpage.*
grep: character class syntax is [[:space:]], not [:space:]
grep: character class syntax is [[:space:]], not [:space:]
jw: There is no frontend called "/docbook/utils-0.6.14/frontends/docbook".
Makefile:1310: recipe for target 'fonts-conf.5' failed
make[2]: *** [fonts-conf.5] Error 2
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/tmp/fontconfig20150511-8139-poipx2/fontconfig-2.11.1/doc'
Makefile:1167: recipe for target 'install' failed
make[1]: *** [install] Error 2
```

**Comment by sjackman** [comment]
Do you have `docbook2x` installed? Does installing `docbook2x` help?

```sh
which -a docbook2man
brew list --versions docbook2x
brew install docbook2x fontconfig
```

**Comment by ntkme** [comment]
No, it doesn't help. It actually has nothing to do with docbook2man. As I said, the problem is on GNU `grep`.

Setting `POSIXLY_CORRECT` forces GNU `grep` behave under posix standard.

**Comment by sjackman** [comment]
Based on [the error message quoted above](https://github.com/Homebrew/linuxbrew/pull/397#issuecomment-101035571) I was guessing that the incorrect usage of grep was in docbook2man. I couldn't find this incorrect usage of grep anywhere in fontconfig. This issue looks like an upstream bug to me. It'd be better to resolve it upstream if possible.

**Comment by sjackman** [comment]
Please report
```sh
which -a docbook2man
docbook2man --version
```

**Comment by ntkme** [comment]
``` sh
$ which -a docbook2man
/data/linuxbrew/bin/docbook2man
/usr/bin/docbook2man
$ docbook2man --version
/data/linuxbrew/bin/docbook2man (part of docbook2X 0.8.8)
$Revision: 1.12 $ $Date: 2006/04/14 17:29:04 $
<URL:http://docbook2x.sourceforge.net/>

Copyright (C) 2003-2004 Steve Cheng
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by sjackman** [comment]
Please report this bug upstream to fontconfig and post a link to the issue here. It would be better fixed upstream in fontconfig than hacked around in Linuxbrew. Thanks for identifying the workaround though.

**Comment by sjackman** [comment]
It's possible that the bug's in a dependency of fontconfig, but maybe the fontconfig developers can help figure out where the true cause lies.

**Comment by ntkme** [comment]
It has been fixed in upstream...

And I found a better workaround for this:

``` sh
brew unlink grep
brew install fontconfig
brew link grep
```

**Pull request closed without merging**
