### PR TITLE
HAProxy fix for linuxbrew

### PR DESCRIPTION
**Pull request by dvbportal**
The original formular does not compile on linux due to USE_KQUEUE=1. I added a condition.

### CODE REVIEW

**Comment by sjackman** [comment]
Can you report the exact error message that you observe?

**Comment by dvbportal** [comment]
The message is:

```
src/ev_kqueue.c:17:23: fatal error: sys/event.h: No such file or directory
 #include <sys/event.h>
                       ^
compilation terminated.
make: *** [src/ev_kqueue.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by sjackman** [comment]
Could a smaller version of this patch work that only disables USE_KQUEUE?
I'm on vacation in Thailand until the new year. Please bump this thread after then. Sorry for the delay.

**Comment by sjackman** [comment]
Try instead
```ruby
      args = %W[
      TARGET=generic
      USE_KQUEUE=#{OS.mac ? "1" : "0"}
      USE_POLL=1
      USE_PCRE=1
      USE_OPENSSL=1
      USE_ZLIB=1
      ADDLIB=-lcrypto
```

**Comment by dvbportal** [comment]
That variant gives me this error:

Error: undefined method `mac' for OS:Module

I also tried:
```
      args = %W[
        TARGET=generic
        USE_KQUEUE=#{OS.mac? ? "1" : "0"}
        USE_POLL=1
        USE_PCRE=1
        USE_OPENSSL=1
        USE_ZLIB=1
        ADDLIB=-lcrypto
      ]
```
which is syntactically correct, but the code does not evaluate USE_KQUEUE=0 and still includes
kqueue with the error:
```
src/ev_kqueue.c:17:23: fatal error: sys/event.h: No such file or directory
 #include <sys/event.h>
                       ^
compilation terminated.
```

Do you have other ideas? I understand the need to keep the formular as compact as possible.

**Comment by sjackman** [comment]
Sorry, that was a typo. It should have been `OS.mac?`, as you guessed.

Please report `brew gist-logs haproxy` to troubleshoot why `USE_KQUEUE=#{…}` isn't working.

**Comment by dvbportal** [comment]
Hi, here it is: https://gist.github.com/7ce0b97129d5deb84223

The build option is in place:
-DBUILD_OPTIONS='"USE_ZLIB=1 USE_POLL=1 USE_KQUEUE=0 USE_OPENSSL=1 USE_PCRE=1"'

But the compiler is still called with -DENABLE_KQUEUE. I suspect a bug in the make files.

**Comment by sjackman** [comment]
Does the following work?
```ruby
      args = %W[
        TARGET=generic
        #{"USE_KQUEUE=1" if OS.mac?}
        USE_POLL=1
        USE_PCRE=1
        USE_OPENSSL=1
        USE_ZLIB=1
        ADDLIB=-lcrypto
      ]
```

**Comment by dvbportal** [comment]
No, it produces an empty line.
```
Last 15 lines from /home/ubuntu/.cache/Homebrew/Logs/haproxy/01.make:
2016-01-10 17:29:35 +0100

make
CC=/usr/bin/gcc-4.8
CFLAGS=-Os -w -pipe -march=core2
LDFLAGS=-L/home/ubuntu/.linuxbrew/lib -Wl,-rpath,/home/ubuntu/.linuxbrew/lib
TARGET=generic

USE_POLL=1
USE_PCRE=1
USE_OPENSSL=1
USE_ZLIB=1
ADDLIB=-lcrypto

make: *** empty string invalid as file name.  Stop.
```
Is there any way to supress the empty array entry?

**Comment by sjackman** [comment]
Thanks for your patience. We'll get there. Try using `compact`.

```ruby
      args = %W[
        TARGET=generic
        #{"USE_KQUEUE=1" if OS.mac?}
        USE_POLL=1
        USE_PCRE=1
        USE_OPENSSL=1
        USE_ZLIB=1
        ADDLIB=-lcrypto
      ].compact
```

**Comment by dvbportal** [comment]
Likewise and no worries. The compact does not work as expected though. Still an empty entry.

```
Last 15 lines from /home/ubuntu/.cache/Homebrew/Logs/haproxy/01.make:
2016-01-10 17:51:40 +0100

make
CC=/usr/bin/gcc-4.8
CFLAGS=-Os -w -pipe -march=core2
LDFLAGS=-L/home/ubuntu/.linuxbrew/lib -Wl,-rpath,/home/ubuntu/.linuxbrew/lib
TARGET=generic

USE_POLL=1
USE_PCRE=1
USE_OPENSSL=1
USE_ZLIB=1
ADDLIB=-lcrypto

make: *** empty string invalid as file name.  Stop.
```

**Comment by sjackman** [comment]
Last stab
```ruby
args = %W[
        TARGET=generic
        USE_POLL=1
        USE_PCRE=1
        USE_OPENSSL=1
        USE_ZLIB=1
        ADDLIB=-lcrypto
      ]
args << "USE_KQUEUE=1" if OS.mac?
```

**Comment by dvbportal** [comment]
That works, cool.  I would also like to change the target to linux2628 because every linux kernel supports that nowadays and we get better performance. ok?
 
``` 
   args = %W[
      TARGET=#{OS.mac? ? "generic" : "linux2628"}
      USE_POLL=1
      USE_PCRE=1
      USE_OPENSSL=1
      USE_ZLIB=1
      ADDLIB=-lcrypto
    ]
    args << "USE_KQUEUE=1" if OS.mac?
```

**Comment by sjackman** [comment]
Yeah. Sorry it took so much back and forth. Yeah, okay to the `TARGET= linux2628`.

**Comment by dvbportal** [comment]
Cool. I updated the PR accordingly.

**Comment by sjackman** [comment]
Looks good! Merged. Thanks for your contribution, Hans.

**Pull request closed without merging**
