### PR TITLE
Fix for java dependency check on linux

### PR DESCRIPTION
**Pull request by saketkc**
See: https://github.com/Homebrew/homebrew-science/issues/1605#issuecomment-68510052

### CODE REVIEW

**Comment by sjackman** [comment]
This patch doesn't implement all the functionality of the Mac version. If the `version` argument is specified, it needs to check whether the installed Java version matches the requested version. A simple regex could parse the output of `java -version`.

**Comment by sjackman** [comment]
```
~ ❯❯❯ /usr/libexec/java_home --failfast
/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home
~ ❯❯❯ /usr/libexec/java_home --failfast --version 1.8
/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home
~ ❯❯❯ /usr/libexec/java_home --failfast --version 1.7
Unable to find any JVMs matching version "1.7".
~ ❯❯❯ echo $?
2
```

**Comment by sjackman** [comment]
I committed a mini-fix. It could be improved, but is good enough for now.

**Comment by saketkc** [comment]
`java -version 2>&1 | awk -F '"' '/version/ {print $2}'`?

**Comment by saketkc** [comment]
@sjackman `java -version 2>&1 | awk -F '"' '/version/ {($2 >= "1.7")?err=0:err=1} END{exit err}'`
Is it okay to use pipes with `quiet_system`, best practice wise?

**Comment by saketkc** [comment]
Closing in lieu of #229

**Pull request closed without merging**
