### PR TITLE
Update gh-pages with latest README.md

### PR DESCRIPTION
**Pull request by timwangdev**
Regenerated Github Pages with generator and removed files and translations that is outdated and unused.

### CODE REVIEW

**Comment by timwangdev** [comment]
You could preview the change at http://github.timwang.me/linuxbrew/

I could help you enhance and add zh-CN translation for the homepage of Linuxbrew if you guys needed.

**Comment by sjackman** [comment]
Hi, Tim. I'm on vacation in Thailand until the new year. Please bump this thread after then. Sorry for the delay.

Thanks for your offer to translate the web page. Please open an issue upstream at Homebrew/Homebrew with your offer to help.

**Comment by timwangdev** [comment]
@sjackman Happy new year! Are you activate right new?

**Comment by sjackman** [comment]
I'm back! I've regenerated the page using the GitHub Pages automatic page generator. The now looks funky to me. Hopefully this is just a cache issue and will resolve itself soon enough.

**Comment by sjackman** [comment]
It was a cache the issue. The page looks good now.

**Pull request closed without merging**
