### PR TITLE
vte 0.29.2: Fix for linuxbrew

### PR DESCRIPTION
**Pull request by paulhybryant**
Fix the error: No package x11 found

### CODE REVIEW

**Comment by paulhybryant** [comment]
Please advise a better way to change the environment variable to build with system x11. Right now this is hard-coded.

**Comment by sjackman** [comment]
Please report `brew environment |grep PKG`.
See https://github.com/Homebrew/linuxbrew/blob/master/Library/Homebrew/extend/ENV/std.rb#L27-L29
and https://github.com/Homebrew/linuxbrew/blob/master/Library/Homebrew/extend/ENV/std.rb#L96-L103
and https://github.com/Homebrew/linuxbrew/blob/master/Library/Homebrew/extend/ENV/std.rb#L250-L254

**Comment by sjackman** [comment]
Also see http://ilgthegeek.livius.net/2015/02/05/pkg-config-search-path/
for an explanation of `PKG_CONFIG_PATH` and `PKG_CONFIG_LIBDIR`.

**Comment by paulhybryant** [comment]
brew environment | grep PKG
returns
export PKG_CONFIG_LIBDIR="$HOME/.linuxbrew/lib/pkgconfig:/usr/lib/pkgconfig"

From https://github.com/Homebrew/linuxbrew/blob/master/Library/Homebrew/extend/ENV/std.rb#L96-L103
It seems /usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig should also be added in the env variable?

**Comment by sjackman** [comment]
I'd be more include to remove system pkg-config paths from the default `PKG_CONFIG_LIBDIR`, including `/usr/lib/pkgconfig`.
https://github.com/Homebrew/linuxbrew/blob/master/Library/Homebrew/extend/ENV/std.rb#L101

**Comment by paulhybryant** [comment]
I have updated the pull request.

**Comment by sjackman** [comment]
I've merged the backend chunk. I haven't merged the `pkgconfig` chunk. I need to think more about how the `pkgconfig` search path should be handled. Thanks for your contribution, Paul.

**Comment by paulhybryant** [comment]
Sure. But without the pkgconfig trunk, the build error will still be there when installing vte.

A potential solution could be to modify the code here
https://github.com/Homebrew/linuxbrew/blob/master/Library/Homebrew/extend/ENV/std.rb#L250-L254

The system pkgconfig path can be added here for x11

**Comment by sjackman** [comment]
Possible. You can also symlink those `pkgconfig` files into `$HOMEBREW_PREFIX/lib/pkgconfig`.

**Comment by sjackman** [comment]
You can also fake a `xorg` package like so:
```sh
mkdir -p `brew --prefix`/Cellar/xorg/7.7/lib/pkgconfig
ln -s /usr/lib64/pkgconfig/x*.pc `brew --prefix`/Cellar/xorg/7.7/lib/pkgconfig/
brew link xorg
```

**Comment by paulhybryant** [comment]
Sure. There can be many ways to have it build successfully. It would be ideal that a formula just works out of the box.

Faking a package is new to me. Thanks for the tip :P.

**Comment by sjackman** [comment]
I removed `/usr/lib/pkgconfig` from `PKG_CONFIG_LIBDIR` in 8c34ef1cab453d4d7a86119c10314b378a08190e

There's a `brew diy` for the purpose of faking packages. I always just do it the manual way. I think it would be helpful to have a command to help users' fake packages for software provided by their system, such as compilers, X, et c.

**Comment by paulhybryant** [comment]
Just want to revisit the issue brought up here.

Faking a package by creating symlinks and link the fake package works, but it is inconvenient sometimes. For example, when I try to link the pkgconfigs for x11, they have their own dependencies (e.g. xcb requires pthread-stubs'). We will have to create symlinks for all its dependencies.
Appending the system pkgconfig paths to the pkgconfig ENV vars seem to be more convenient.

The brew diy command doesn't seem to be documented. Can you elaborate a bit how it works with an example?

Thanks,

**Comment by sjackman** [comment]
I'm on vacation until the new year. brew diy is intended to install a tarball (that uses autoconf or cmake) that doesn't have a formula. Linxubrew is easier to debug when it doesn't use system libraries, which vary a lot between distributions. I'd like to package X11 client libraries for Linuxbrew,

**Pull request closed without merging**
