### PR TITLE
New formula: strace

### PR DESCRIPTION
**Pull request by tomas**
One of the most useful debugging tools that we have on Linux.

http://sourceforge.net/projects/strace/

I read the cookbook and I *think* I have everything covered. This is my first formula submission so sorry if there's something I missed!

### CODE REVIEW

**Comment by sjackman** [comment]
```
❯❯❯ lbrew audit --strict strace

==> brew style strace

1 file inspected, no offenses detected

==> audit problems
strace:
 * `checksum` (line 7) should be put before `head` (line 4)
 * Stable: version 4.10 is redundant with version scanned from URL
 * Stable: Please use https:// for http://downloads.sourceforge.net/project/strace/strace/4.10/strace-4.10.tar.xz
 * HEAD: Redundant :using value in URL
 * Commented-out dep "perl" => :optional
```

**Comment by tomas** [comment]
Cool, thanks.

Should I fix those issues and push the changes?

**Comment by sjackman** [comment]
Yes, please. Please also squash the commits into a single commit.

**Comment by tomas** [comment]
Done.

**Comment by sjackman** [comment]
Merged. Thanks for your very useful contribution, Tomás.

**Comment by tomas** [comment]
But of course -- thank *you* for an amazing package manager. :)

Do you guys keep a "want list" of missing packages that need formulae?

**Comment by sjackman** [comment]
My pleasure. Just the issues and pull requests.

**Pull request closed without merging**
