### PR TITLE
zsh: Depends on texinfo

### PR DESCRIPTION
**Pull request by paulhybryant**
Add zsh dependency texinfo.

### CODE REVIEW

**Comment by sjackman** [comment]
Please add `unless OS.mac?`
```ruby
depends_on "texinfo" unless OS.mac?`
```

Please report the exact error message that you see without using this patch.

**Comment by sjackman** [comment]
The commit log message should be
`zsh: Depends on texinfo for Linuxbrew`

**Comment by paulhybryant** [comment]
The error without this patch is

/bin/sh: line 3: makeinfo: command not found
make[1]: *** [install.info] Error 1
make[1]: Leaving directory `/tmp/zsh20150713-13485-19a2t7g/zsh-5.0.8/Doc'
make: *** [install.info] Error 2

**Comment by paulhybryant** [comment]
The change and message are updated.

**Comment by sjackman** [comment]
Merged. Thanks for your contribution, Paul.

**Pull request closed without merging**
