### PR TITLE
git 2.3.0

### PR DESCRIPTION
**Pull request by iggyvolz**
New git update just came out today.  https://github.com/blog/1957-git-2-3-has-been-released

### CODE REVIEW

**Comment by sjackman** [comment]
I merge Homebrew once per week into Linuxbrew, usually on Monday.

**Comment by sjackman** [comment]
PRs for new versions of software should be opened at Homebrew/homebrew, rather than Homebrew/linuxbrew.

**Comment by sjackman** [comment]
I've merged just now. Enjoy.

**Comment by iggyvolz** [comment]
Oh, I wasn't aware everything came from Homebrew.

**Pull request closed without merging**
