### PR TITLE
freeimage (3.17.0)

### PR DESCRIPTION
**Pull request by davydden**
fix for gcc-5 and corrected patches in makefiles.

### CODE REVIEW

**Comment by sjackman** [comment]
This should be sent upstream to Homebrew if it addresses compiler errors with GCC 5 on Mac as well as Linux.

**Comment by davydden** [comment]
it's not only that! it's also changes of `.dylib` to `.so` in patches. So the one you have in Linuxbrew is not working irrespectively of gcc version.

**Comment by davydden** [comment]
i submitted gcc related stuff here: https://github.com/Homebrew/homebrew/pull/44612

**Comment by sjackman** [comment]
This patch is too big for me to merge into Linuxbrew. My recommendation would be to pull the inline patch out into gist and send what portion of this patch upstream to Homebrew/homebrew that isn't specific to Linux. Send the remaining portion that's specific to Linux here to Homebrew/linuxbrew.

**Comment by davydden** [comment]
i already send the gcc-related part to homebrew (see link above). Once it's merged/resolved there, i will update the PR here.

**Comment by sjackman** [comment]
Great. Thanks, Denis. Blocked on Homebrew/homebrew#44612

**Comment by davydden** [comment]
fixed in upstream. After you merge it I will rebase this PR.

**Comment by sjackman** [comment]
Thanks, Denis. The merge will come in the new year.

**Comment by sjackman** [comment]
I've merged Homebrew into Linuxbrew.

**Comment by davydden** [comment]
i've rebased

**Comment by sjackman** [comment]
This patch is too large for Linuxbrew.
Does it work to simply change
```ruby
  patch :DATA
```
to
```ruby
  patch :DATA if OS.mac?
```

**Comment by davydden** [comment]
are you sure you are looking at the right version? The patch is roughly the same number of lines as the one in Homebrew. I just modified it to work on Linux.

**Comment by sjackman** [comment]
Yep. [Showing  1 changed file  with 20 additions and 56 deletions.](https://github.com/Homebrew/linuxbrew/pull/559/files)

Does it work if you simply disable this patch as above?

**Comment by davydden** [comment]
i don't need to disable it to see that it will not work otherwise ;-)
seriously, just see what it does to Makefile which grants a working installation.

**Comment by sjackman** [comment]
That whole patch appears to be Mac specific. Try disabling it.

**Comment by davydden** [comment]
[these](https://github.com/davydden/linuxbrew/blob/freeimage_linuxbrew/Library/Formula/freeimage.rb#L97-L101) and [these](https://github.com/davydden/linuxbrew/blob/freeimage_linuxbrew/Library/Formula/freeimage.rb#L109-L110) and [these](https://github.com/davydden/linuxbrew/blob/freeimage_linuxbrew/Library/Formula/freeimage.rb#L118-L123) lines in the patch have nothing to do with MAC and as I said they grant working installation. 
The mac-version is similar in that sense.

**Comment by davydden** [comment]
to close this topic once and forever, ignoring the patch gives:
```
Last 15 lines from /home/davydden/Library/Logs/Homebrew/freeimage/02.make:
2016-01-07 10:52:19 +0100

make
-f
Makefile.gnu
install
PREFIX=/home/davydden/.linuxbrew/Cellar/freeimage/3.17.0

install -d //usr/include //usr/lib
install -m 644 -o root -g root Source/FreeImage.h //usr/include
install: cannot create regular file ‘//usr/include/FreeImage.h’: Permission denied
make: *** [install] Error 1
```

**Comment by sjackman** [comment]
Okay. Have you sent this patch to the upstream author? https://github.com/davydden/linuxbrew/blob/freeimage_linuxbrew/Library/Formula/freeimage.rb#L45-L127

**Comment by davydden** [comment]
upstream is already fine. I have not changed this part of the patch in the upstream, it was working without any issues. On the contrary, I **adjusted** this patch to work for Linux. That's what the whole PR is about...

**Comment by sjackman** [comment]
I wasn't clear enough. I meant have you sent this patch upstream to the freeimage author.

I don't want to merge this patch as it is now for two reasons. One, it breaks the build on Mac OS and Linuxbrew aims to be compatible with both Mac and Linux. Two, if Homebrew changes the patch for Mac it will create merge conflicts when I merge Homebrew into Linuxbrew.

I suggest gist-ing your patch for Linux, and patching this formula like so:
```ruby
if OS.mac?
  patch :DATA
else
  patch do
    …
  end
end
```

**Comment by davydden** [comment]
it does not have to be sent upstream to freeimage. It mostly settings for makefile, it does not fix any bugs.

**Comment by davydden** [comment]
I will shift it to the gist later....

**Comment by davydden** [comment]
@sjackman i shifted it to the gist

**Comment by sjackman** [comment]
Thanks for your contribution, Davy. For future contributions, the preferred commit log message is
`freeimage 3.17.0: Fix for Linuxbrew`

**Comment by davydden** [comment]
@sjackman I am Denis :smile:

**Comment by sjackman** [comment]
:blush: My apologies, Denis.

**Pull request closed without merging**
