### PR TITLE
Upgrade jdk formula to jdk 1.8.0_40

### PR DESCRIPTION
**Pull request by aruizca**

### CODE REVIEW

**Comment by Mikaela** [comment]
I think this should go to [Homebrew](https://github.com/Homebrew/Homebrew).

**Comment by aruizca** [comment]
Thanks

**Comment by sjackman** [comment]
On Mac, the JDK formula is in Homebrew-cask, but there is no cask support for Linuxbrew.

**Comment by sjackman** [comment]
Thanks for your contribution, Angel.

**Pull request closed without merging**
