### PR TITLE
Update git to 2.5.3

### PR DESCRIPTION
**Pull request by gcstang**
Git update to 2.5.3

### CODE REVIEW

**Comment by Mikaela** [comment]
All updates and new formulass hould go to https://github.com/homebrew/homebrew which is merged here once a week.

**Comment by DomT4** [comment]
Aye. I think @sjackman is away at the moment, but it should be done reasonably soon. Thanks for the submission though!

**Comment by gcstang** [comment]
I submitted this because git is still at 2.5.0 which is quite old it was put out on 27-Jul-2015 and there have been a lot of fixes since (2.5.3 was released recently and most important 2.5.1 had a LOT of fixes).

Thank you for a great project.

**Comment by DomT4** [comment]
No worries. It just causes potential merge problems for Shaun when he re-syncs the repos, when merging the two repos is already not a fun task. I'll try and find out if anyone knows when Shaun is expected to be available again.

**Comment by gcstang** [comment]
Ok, sounds great.

Thank you for your reply and help.

**Comment by sjackman** [comment]
I'm back for two more weeks and then gone for two more months. I'm on parental leave. Sorry for the delays that my leave is causing. I'm hoping to bring on more people to help with Linuxbrew.

**Comment by DomT4** [comment]
Is there anyone else who regularly helps with Linuxbrew, or has the knowledge & willingness to do so?

**Comment by sjackman** [comment]
@tdsmith Is very helpful and trying not to become a Linuxbrew maintainer.
I've met with @danabrand who is interested and works in systems at UBC.
Some @Homebrew/science people use Linuxbrew.

**Pull request closed without merging**
